apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_DB: cGlwZWxpbmVz # base64 encoded value of 'pipelines'
  POSTGRES_USER: YWRtaW4=  # base64 encoded value of 'admin'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded value of 'password'
  