app:
  profiling: false                 # Enable for development if needed
  pipeline_template: "pipelines/benthos/pipeline.yaml"
  generated_pipeline_config: "pipelines/benthos/generated-pipeline.yaml"
  source:
    parser: "json"                 # Supported parsers: json, avro, parquet
    plugin_path: "/app/bin/plugins/json.so"
  kafka:
    brokers: ["redpanda:9092"]     # Use the hostname of the Kafka broker
    topics: ["pipeline-topic"]
    consumer_group: "pipeline-group"
    min_partitions: 3
  postgres:
    url: "postgresql://admin:password@postgres:5432/pipelines?sslmode=disable"
    table: "processed_data"
  logger:
    level: "TRACE"