apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
  namespace: dev
spec:
  type: ClusterIP # Use ClusterIP for services accessed via Ingress
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: grafana
