apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: prometheus
  name: prometheus
  namespace: dev
spec:
  type: ClusterIP # Use ClusterIP for services accessed via Ingress
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: prometheus
