apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: dev
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: redpanda
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: admin
      port: 9644
      targetPort: 9644
    - name: rpc
      port: 4195
      targetPort: 4195
  selector:
    app: redpanda
  type: NodePort
  