apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redpanda
  name: redpanda
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9644"
      port: 9644
      targetPort: 9644
    - name: "4195"
      port: 4195
      targetPort: 4195
  selector:
    io.kompose.service: redpanda
