input:
  kafka:
    addresses: ["localhost:9092"]
    topics: ["test-topic"]
    consumer_group: "test-group"

pipeline:
  processors:
    - mapping: |
        root.id = uuid_v4()
        root.timestamp = now()
        root.data = content().uppercase()

output:
  broker:
    outputs:
      - sql_insert:
          driver: postgres
          dsn: "postgresql://admin:password@localhost:5432/pipelines?sslmode=disable"
          table: "processed_data"
          columns: ["id", "timestamp", "data"]
          args_mapping: |
            root = [
              this.id,
              this.timestamp,
              this.data
            ]
      - kafka:
          addresses: ["localhost:9092"]
          topic: "failed-messages"
      - stdout:
          codec: lines

metrics:
  prometheus:
    push_url: "http://localhost:9091"
    push_interval: "10s"
    push_job_name: "redpanda_connect"

logger:
  level: DEBUG
