name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go (if required for your project)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: make deps  # Replace 'deps' if a dependency task is defined in your Makefile
        shell: bash

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: make test
        shell: bash

      # Step 5: Run Integration Plugin Tests
      - name: Run Integration Plugin Tests
        run: make test-integration-plugin
        shell: bash

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: r9docker/ddpm:latest
