name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Step 3: Run Unit Tests
      - name: Run Unit Tests
        run: make test
        shell: bash
      
      # Step 4: Run Integration Plugin Tests
      - name: Run Integration Plugin Tests
        run: make test-integration-plugin
        shell: bash

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: make docker-build
        shell: bash

      # Step 7: Push Docker Image
      - name: Push Docker Image
        run: docker push r9docker/ddpm:latest
